services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_node
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI

  user_service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo # Ensure mongo starts before user_service as user_service depends on it(mongo)

  task_service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo # Ensure mongo starts before user_service as user_service depends on it(mongo)
      - rabbitmq # Ensure rabbitmq starts before task_service as task_service depends on it(rabbitmq)

  notification_service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq
volumes:
  mongo_data:
    driver: local
